version: '3'

services:
    djangoapp:
        build: .
        volumes:
            - .:/opt/services/djangoapp/src
        networks:
            - nginx_network
    
    nginx:
        image: nginx:latest
        ports:
            - 6060:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - djangoapp
        networks:
            - nginx_network

networks:
    nginx_network:
        driver: bridge